<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container04n5Y1E\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container04n5Y1E/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container04n5Y1E.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container04n5Y1E\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container04n5Y1E\App_KernelDevDebugContainer([
    'container.build_hash' => '04n5Y1E',
    'container.build_id' => '875c06df',
    'container.build_time' => 1626045977,
], __DIR__.\DIRECTORY_SEPARATOR.'Container04n5Y1E');
